### ISSUE TITLE
service-daemon script has CRLF endings

### ISSUE THREAD

**Issue by emahuni** [Neo-Oli/termux-services#2]
Because of that, on unix it throws `data/data/com.termux/files/usr/bin/bash^M: bad interpreter: No such file or directory`

Please use:
`pkg install dos2unix`
then 
`dos2unix service-daemon`
to fix the issue.

**Comment by Neo-Oli** [comment]
This doesn't seem to be the case in this repository. Running dos2unix doesn't cause any unstaged changes in git. Also your script seems to have local modifications, because the shebang usually points to `sh` and not `bash`. Could this problem have been introduced on your side?
