### ISSUE TITLE
unable to change to service directory: file does not exist

### ISSUE THREAD

**Issue by mizzunet** [Neo-Oli/termux-services#7]
I having `unable to change to service directory: file does not exist` for any service

```
u0_a140@localhost ~ [100]> sv up docker
fail: docker: unable to change to service directory: file does not exist
u0_a140@localhost ~ [1]> sv up crond
fail: crond: unable to change to service directory: file does not exist
```

What could be causing this?

**Comment by Neo-Oli** [comment]
This is no longer the repository. The Services repository is hosted at: https://github.com/termux/termux-services

Though your issue can be fixed by restarting or by running `service-daemon start`
